---
#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                   Define global settings
  hosts:                  localhost
  connection:             local
  gather_facts:           no

  vars_files:
     - ./global-vars/apic-details.yaml

  tasks:
    - name:
      set_fact:
        desired_state:    present
        #desired_state:    absent
        #desired_status:   modified,created
        #desired_status:   deleted

    - name:               apic details
      set_fact:
        apic_info:        &apic_info
          host:           "{{ apic_info.host }}"
          username:       "{{ apic_info.username }}"
          password:       "{{ apic_info.password }}"
          validate_certs: no

        rest_info:        &rest_info
          use_proxy:      no
          path:           /api/mo/.json
          method:         post
  tags:                   always

#==============================================================================================
# Begin Plays
#
# Available Tags:
#               snapshot
#               tenants
#==============================================================================================
- import_playbook:        ./snapshot.yaml
  vars:
    snapshotDescription:  Prior-to-configuring-Tenants
  tags:                   snapshot

#==============================================================================================
# Add Tenants
#==============================================================================================
- name:                   Manage Tenants
  hosts:                  localhost
  connection:             local
  gather_facts:           no

  vars_files:
     - ./global-vars/tenants.yaml

  tasks:
    - name:               Create/Delete Tenants
      aci_tenant:
        <<:               *apic_info
        tenant:           "{{ item.tenant }}"
        description:      "{{ item.descr }}"
        state:            "{{ desired_state }}"
      loop:
        "{{tenants}}"
      tags:               tenants
