---
#==============================================================================================
# Global Configuration
#==============================================================================================
- name:                   Define global settings
  hosts:                  localhost
  connection:             local
  gather_facts:           no

  vars_files:
     - ../../../global-vars/apic-details.yaml

  tasks:
    - name:
      set_fact:
        desired_state:    present
        #desired_state:   absent
        #desired_status:  modified,created
        #desired_status:  deleted

    - name:               apic details
      set_fact:
        apic_info:        &apic_info
          host:           "{{ apic_info.host }}"
          username:       "{{ apic_info.username }}"
          password:       "{{ apic_info.password }}"
          validate_certs: no

        rest_info:        &rest_info
          use_proxy:      no
          path:           /api/mo/.json
          method:         post
  tags:                   always

#==============================================================================================
# Begin Plays
#
# Available Tags:
#               snapshot
#               filters
#               contract
#               subject
#               aci_contract_subject_to_filter
#               bind-contract
#==============================================================================================
- import_playbook:        ../../../snapshot.yaml
  vars:
    snapshotDescription:  Prior to configuring Contracts in the ctf tenant - Created by Ansible
  tags:                   snapshot

#==============================================================================================
# Create the filters
#==============================================================================================
- name:                               Configure filters
  hosts:                              localhost
  connection:                         local
  gather_facts:                       no

  vars_files:
     - ./vars/contract-vars.yaml

  tasks:
    - name:                           Create Filter
      aci_filter:
        <<:                           *apic_info
        tenant:                       "common"
        filter:                       "{{ item.subject }}_src_port_{{ item.src_port }}_to_dst_port_{{ item.dst_port }}"
        state:                        "{{ desired_state }}"
      with_items:
        "{{ contract }}"
      loop_control:
        pause: 1

# Create a new filter entry
    - name:                           Create Filter Entry
      aci_filter_entry:
        <<:                           *apic_info
        filter:                       "{{ item.subject }}_src_port_{{ item.src_port }}_to_dst_port_{{ item.dst_port }}"
        entry:                        "src_port_{{ item.src_port }}_to_dst_port_{{ item.dst_port }}"
        tenant:                       "common"
        ether_type:                   "ip"
        ip_protocol:                  "{{ item. subject }}"
        dst_port:                     "{{ item.dst_port }}"
        state:                        "{{ desired_state }}"
      with_items:
        "{{ contract }}"
      loop_control:
        pause: 1
  tags:                               filters

#==============================================================================================
# Add the contracts
#==============================================================================================
# naming structure:                   consumer tenant|app|epg to provider tenant|app|epg
- name:                               Configure contracts between epgs
  hosts:                              localhost
  connection:                         local
  gather_facts:                       no

  vars_files:
     - ./vars/contract-vars.yaml

  tasks:
    - name:                           Add a new contract
      aci_contract:
        <<:                           *apic_info
        tenant:                       "{{ item.cons_tn_name }}"
        contract:                     "{{ item.cons_tn_name }}_{{ item.cons_ap_name }}_{{ item.cons_epg_name }}_to_{{ item.prov_tn_name }}_{{ item.prov_ap_name }}_{{ item.prov_epg_name }}"
        description:                  "{{ item.description }}"
        scope:                        "{{ item.scope }}"
        state:                        "{{ desired_state }}"
      with_items:
        "{{ contract }}"
      loop_control:
        pause: 1
      tags:                           contract

    - name:                           Add a new contract subject
      aci_contract_subject:
        <<:                           *apic_info
        tenant:                       "{{ item.cons_tn_name }}"
        contract:                     "{{ item.cons_tn_name }}_{{ item.cons_ap_name }}_{{ item.cons_epg_name }}_to_{{ item.prov_tn_name }}_{{ item.prov_ap_name }}_{{ item.prov_epg_name }}"
        subject:                      "{{ item.subject }}"
        description:                  ""
        reverse_filter:               yes
#        priority:                    ""
#        dscp:                        ""
        state:                        "{{ desired_state }}"
      with_items:
        "{{ contract }}"
      loop_control:
        pause: 1
      tags:                           subject

    - name:                           Add a new contract subject to filter binding
      aci_contract_subject_to_filter:
        <<:                           *apic_info
        tenant:                       "{{ item.cons_tn_name }}"
        contract:                     "{{ item.cons_tn_name }}_{{ item.cons_ap_name }}_{{ item.cons_epg_name }}_to_{{ item.prov_tn_name }}_{{ item.prov_ap_name }}_{{ item.prov_epg_name }}"
        subject:                      "{{ item.subject }}"
        filter:                       "{{ item.subject }}_src_port_{{ item.src_port }}_to_dst_port_{{ item.dst_port }}"
  #      log:                         none
        state:                        "{{ desired_state }}"
      with_items:
        "{{ contract }}"
      loop_control:
        pause: 1
      tags:                           subject-to-filter

#==============================================================================================
# Bind the contracts
#==============================================================================================
# naming structure:                   consumer tenant|app|epg to provider tenant|app|epg
- name:                               Configure contracts between tenants
  hosts:                              localhost
  connection:                         local
  gather_facts:                       no

  vars_files:
     - ./vars/contract-vars.yaml

  tasks:
    - name:                           Bind Contract to Destination EPG
      aci_epg_to_contract:
        <<:                           *apic_info
        tenant:                       "{{ item.cons_tn_name }}"
        ap:                           "{{ item.cons_ap_name }}"
        epg:                          "{{ item.cons_epg_name }}"
        contract:                     "{{ item.cons_tn_name }}_{{ item.cons_ap_name }}_{{ item.cons_epg_name }}_to_{{ item.prov_tn_name }}_{{ item.prov_ap_name }}_{{ item.prov_epg_name }}"
        contract_type:                consumer
        state:                        "{{ desired_state }}"
      with_items:
        "{{ contract }}"
      loop_control:
        pause: 1

    - name:                           Bind Contract to Source EPG
      aci_epg_to_contract:
        <<:                           *apic_info
        tenant:                       "{{ item.prov_tn_name }}"
        ap:                           "{{ item.prov_ap_name }}"
        epg:                          "{{ item.prov_epg_name }}"
        contract:                     "{{ item.cons_tn_name }}_{{ item.cons_ap_name }}_{{ item.cons_epg_name }}_to_{{ item.prov_tn_name }}_{{ item.prov_ap_name }}_{{ item.prov_epg_name }}"
        contract_type:                provider
        state:                        "{{ desired_state }}"
      with_items:
        "{{ contract }}"
      loop_control:
        pause: 1
  tags:                               bind-contract
